apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
  {{- if .Values.mysql.enabled }}
    app: "xwiki-{{ .Chart.AppVersion }}-lts-mysql-tomcat"
  {{- else if .Values.postgresql.enabled }}
    app: "xwiki-{{ .Chart.AppVersion }}-lts-postgres-tomcat"
  {{- else }}
    app: xwiki-{{ .Chart.AppVersion }}-{{ .Values.image.tag }}
  {{- end }}
    version: "{{ .Chart.AppVersion }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "fullname" . }} # has to match .spec.template.metadata.labels
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      containers:
      - name: {{ .Chart.Name }}
      {{- if .Values.mysql.enabled }}
        image: "xwiki:lts-mysql-tomcat"
      {{- else if .Values.postgresql.enabled }}
        image: "iplaman/xwiki:12.5.1"
      {{- else }}
        image: xwiki:{{ .Values.image.tag }}
      {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        env:
        - name: JAVA_OPTS
          value: "-Xmx2048m"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
        {{- if .Values.mysql.enabled }}
              name: "{{ .Release.Name }}-mysql"
              key: mysql-password
        {{- else if .Values.postgresql.enabled }}
              name: "{{ .Release.Name }}-postgresql"
              key: postgresql-password
        {{- else }}
              name: {{ .Release.Name | quote }}
              key: DB_PASSWORD
        {{- end }}
        {{- if .Values.solr.enabled }}
        - name: INDEX_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: INDEX_HOST
        - name: INDEX_PORT
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: INDEX_PORT
        {{- end }}
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_HOST
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_USER
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: {{ template "fullname" . }}
              key: DB_DATABASE
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
        - name: xwiki-data
          mountPath: /opt/solr/server/solr
      volumes:
      - name: xwiki-data
        persistentVolumeClaim:
          claimName: xwiki
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: xwiki
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage }}
    {{- if .Values.storageClass }}
    storageClassName: {{ .Values.storageClass | quote }}
    {{- end }}
