{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
  {{- if .Values.ingress.annotations }}
      {{ toYaml .Values.ingress.annotations | indent 0 }}
  {{- end }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  rules:
  - host: myxwiki.example.com
    http:
      paths:
      - backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80
  tls:
  - hosts:
    - myxwiki.example.com
{{- end -}}